defaultSemverRangePrefix: ""

enableGlobalCache: true

enableTransparentWorkspaces: true

nodeLinker: node-modules

unsafeHttpWhitelist:
  - mirrors.cloud.tencent.com

yarnPath: ".yarn/releases/yarn-berry.cjs"
