defaultSemverRangePrefix: ""

enableGlobalCache: true

enableTransparentWorkspaces: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist:
  - mirrors.cloud.tencent.com
  - mirrors.tencent.com

yarnPath: .yarn/releases/yarn-3.7.0.cjs
