defaultSemverRangePrefix: ""

enableGlobalCache: true

enableTransparentWorkspaces: false

nodeLinker: node-modules

unsafeHttpWhitelist:
  - mirrors.cloud.tencent.com
  - mirrors.tencent.com

yarnPath: .yarn/releases/yarn-3.2.0.cjs
