name: CI

on:
  push:
    branches:
      - main
  pull_request:
  # schedule:
  #   - cron: "0 23 * * 6"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        PLATFORM:
          - "ubuntu-latest"
          # - "macos-latest"
          # - "windows-latest"
        NODE:
          - "16"
          - "14"
          - "12"
        # exclude:
        #   - PLATFORM: "macos-latest"
        #     NODE: "12"

    name: Test on node ${{ matrix.NODE }} and ${{ matrix.PLATFORM }}
    runs-on: ${{ matrix.PLATFORM }}
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    # needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NODE }}

      - name: Install Dependencies
        run: yarn

      # - name: Download Artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: dist
      #     path: dist

      - name: Run Test
        run: yarn test

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        if: success()
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn

      - name: Build Package
        run: yarn build
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dist
      #     path: dist
